/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'clinician-copy': ClinicianCopy;
  };
  globalsSelect: {
    'clinician-copy': ClinicianCopySelect<false> | ClinicianCopySelect<true>;
  };
  locale: null;
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Prefilled with current copy for Home, Contact, Therapy, About, Billing, Resources, and Intensive routes.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clinician-copy".
 */
export interface ClinicianCopy {
  id: number;
  home?: {
    heroHeadline?: string | null;
    heroSubhead?: string | null;
    connectionBandTitle?: string | null;
    connectionBandBody?:
      | {
          text?: string | null;
          id?: string | null;
        }[]
      | null;
    waysTitle?: string | null;
    waysSubtitle?: string | null;
    nextStepTitle?: string | null;
    nextStepBody?: string | null;
    intensiveTitle?: string | null;
    intensiveBody?: string | null;
    intensiveCtaLabel?: string | null;
    videoTitle?: string | null;
    videoDescription?: string | null;
  };
  contact?: {
    heroTitle?: string | null;
    heroSubtitle?: string | null;
    contactIntro?: string | null;
    contactBody?: string | null;
    contactDetailsTitle?: string | null;
    contactDetails?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    formTitle?: string | null;
    formNameLabel?: string | null;
    namePlaceholder?: string | null;
    formEmailLabel?: string | null;
    emailPlaceholder?: string | null;
    formMessageLabel?: string | null;
    messagePlaceholder?: string | null;
    formHelperText?: string | null;
    submitLabel?: string | null;
    submittingLabel?: string | null;
    successMessage?: string | null;
    errorMessage?: string | null;
    spamBlockedMessage?: string | null;
    faqTitle?: string | null;
    faqItems?:
      | {
          question: string;
          answer: string;
          id?: string | null;
        }[]
      | null;
    serviceAreaTitle?: string | null;
    serviceAreaBody?: string | null;
    hoursTitle?: string | null;
    hoursItems?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    ratesTitle?: string | null;
    ratesSubtitle?: string | null;
  };
  therapy?: {
    setupTitle?: string | null;
    setupSubhead?: string | null;
    servicesTitle?: string | null;
    howItWorksTitle?: string | null;
    faqTitle?: string | null;
    faqItems?:
      | {
          question: string;
          answer: string;
          id?: string | null;
        }[]
      | null;
    resourceTitle?: string | null;
    resourceBody?: string | null;
    resourceCtaLabel?: string | null;
    intensiveTitle?: string | null;
    intensiveBody?: string | null;
    intensiveCtaLabel?: string | null;
  };
  about?: {
    nameTitle?: string | null;
    heroSubtitle?: string | null;
    credentialResumeTitle?: string | null;
    modalitiesBandTitle?: string | null;
    modalitiesBandIntro?: string | null;
    goodFitTitle?: string | null;
    goodFitBody?: string | null;
    approachTitle?: string | null;
    systemicThinkerTitle?: string | null;
    systemicThinkerBody?: string | null;
    areasOfInterestTitle?: string | null;
    talkingAboutSexTitle?: string | null;
    faqTitle?: string | null;
    faqItems?:
      | {
          question: string;
          answer: string;
          id?: string | null;
        }[]
      | null;
  };
  billing?: {
    heroTitle?: string | null;
    heroSubtitle?: string | null;
    primaryCtaLabel?: string | null;
    secondaryCtaLabel?: string | null;
    privatePayTitle?: string | null;
    superbillsTitle?: string | null;
    superbillsBody?: string | null;
    howItWorksTitle?: string | null;
    howItWorksNote?: string | null;
    diagnosisTitle?: string | null;
    beforeStartTitle?: string | null;
    beforeStartBody?: string | null;
    faqTitle?: string | null;
    faqItems?:
      | {
          question: string;
          answer: string;
          id?: string | null;
        }[]
      | null;
    closingCtaTitle?: string | null;
    closingCtaBody?: string | null;
    closingCtaLabel?: string | null;
  };
  resources?: {
    v2Title?: string | null;
    v2Summary?: string | null;
    keyConceptsTitle?: string | null;
  };
  intensive?: {
    heroHeading?: string | null;
    heroSubhead?: string | null;
    sellLead?: string | null;
    sellTitle?: string | null;
    sellBodyOne?: string | null;
    sellBodyTwo?: string | null;
    sellOutcome?: string | null;
    includedTitle?: string | null;
    includedItems?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    waitlistCtaTitle?: string | null;
    waitlistCtaBody?: string | null;
    faqTitle?: string | null;
    faqItems?:
      | {
          question: string;
          answer: string;
          id?: string | null;
        }[]
      | null;
  };
  themes?: {
    sectionEyebrow?: string | null;
    sectionTitle?: string | null;
    sectionBody?: string | null;
    relatedThemesTitle?: string | null;
    relatedThemesBody?: string | null;
    quotesTitle?: string | null;
    quotesBody?: string | null;
    quoteSourcePrefix?: string | null;
    quoteThemePrefix?: string | null;
    backToIntensiveLabel?: string | null;
    waitlistCtaLabel?: string | null;
    waitlistCtaHref?: string | null;
    quotes?:
      | {
          themeSlugs: (
            | 'before-we-commit'
            | 'making-a-decision'
            | 'important-transition'
            | 'breach-of-trust'
            | 'loss-of-spark-sexual-challenges'
            | 'is-this-the-end'
          )[];
          quote: string;
          practitioner: string;
          sourceTitle: string;
          sourceUrl: string;
          id?: string | null;
        }[]
      | null;
    entries?:
      | {
          slug:
            | 'before-we-commit'
            | 'making-a-decision'
            | 'important-transition'
            | 'breach-of-trust'
            | 'loss-of-spark-sexual-challenges'
            | 'is-this-the-end';
          navLabel?: string | null;
          title?: string | null;
          subtitle?: string | null;
          intro?: string | null;
          fitTitle?: string | null;
          fitBullets?:
            | {
                text: string;
                id?: string | null;
              }[]
            | null;
          outcomesTitle?: string | null;
          outcomesBullets?:
            | {
                text: string;
                id?: string | null;
              }[]
            | null;
          faq?:
            | {
                question: string;
                answer: string;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clinician-copy_select".
 */
export interface ClinicianCopySelect<T extends boolean = true> {
  home?:
    | T
    | {
        heroHeadline?: T;
        heroSubhead?: T;
        connectionBandTitle?: T;
        connectionBandBody?:
          | T
          | {
              text?: T;
              id?: T;
            };
        waysTitle?: T;
        waysSubtitle?: T;
        nextStepTitle?: T;
        nextStepBody?: T;
        intensiveTitle?: T;
        intensiveBody?: T;
        intensiveCtaLabel?: T;
        videoTitle?: T;
        videoDescription?: T;
      };
  contact?:
    | T
    | {
        heroTitle?: T;
        heroSubtitle?: T;
        contactIntro?: T;
        contactBody?: T;
        contactDetailsTitle?: T;
        contactDetails?:
          | T
          | {
              text?: T;
              id?: T;
            };
        formTitle?: T;
        formNameLabel?: T;
        namePlaceholder?: T;
        formEmailLabel?: T;
        emailPlaceholder?: T;
        formMessageLabel?: T;
        messagePlaceholder?: T;
        formHelperText?: T;
        submitLabel?: T;
        submittingLabel?: T;
        successMessage?: T;
        errorMessage?: T;
        spamBlockedMessage?: T;
        faqTitle?: T;
        faqItems?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
        serviceAreaTitle?: T;
        serviceAreaBody?: T;
        hoursTitle?: T;
        hoursItems?:
          | T
          | {
              text?: T;
              id?: T;
            };
        ratesTitle?: T;
        ratesSubtitle?: T;
      };
  therapy?:
    | T
    | {
        setupTitle?: T;
        setupSubhead?: T;
        servicesTitle?: T;
        howItWorksTitle?: T;
        faqTitle?: T;
        faqItems?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
        resourceTitle?: T;
        resourceBody?: T;
        resourceCtaLabel?: T;
        intensiveTitle?: T;
        intensiveBody?: T;
        intensiveCtaLabel?: T;
      };
  about?:
    | T
    | {
        nameTitle?: T;
        heroSubtitle?: T;
        credentialResumeTitle?: T;
        modalitiesBandTitle?: T;
        modalitiesBandIntro?: T;
        goodFitTitle?: T;
        goodFitBody?: T;
        approachTitle?: T;
        systemicThinkerTitle?: T;
        systemicThinkerBody?: T;
        areasOfInterestTitle?: T;
        talkingAboutSexTitle?: T;
        faqTitle?: T;
        faqItems?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
      };
  billing?:
    | T
    | {
        heroTitle?: T;
        heroSubtitle?: T;
        primaryCtaLabel?: T;
        secondaryCtaLabel?: T;
        privatePayTitle?: T;
        superbillsTitle?: T;
        superbillsBody?: T;
        howItWorksTitle?: T;
        howItWorksNote?: T;
        diagnosisTitle?: T;
        beforeStartTitle?: T;
        beforeStartBody?: T;
        faqTitle?: T;
        faqItems?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
        closingCtaTitle?: T;
        closingCtaBody?: T;
        closingCtaLabel?: T;
      };
  resources?:
    | T
    | {
        v2Title?: T;
        v2Summary?: T;
        keyConceptsTitle?: T;
      };
  intensive?:
    | T
    | {
        heroHeading?: T;
        heroSubhead?: T;
        sellLead?: T;
        sellTitle?: T;
        sellBodyOne?: T;
        sellBodyTwo?: T;
        sellOutcome?: T;
        includedTitle?: T;
        includedItems?:
          | T
          | {
              text?: T;
              id?: T;
            };
        waitlistCtaTitle?: T;
        waitlistCtaBody?: T;
        faqTitle?: T;
        faqItems?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
      };
  themes?:
    | T
    | {
        sectionEyebrow?: T;
        sectionTitle?: T;
        sectionBody?: T;
        relatedThemesTitle?: T;
        relatedThemesBody?: T;
        quotesTitle?: T;
        quotesBody?: T;
        quoteSourcePrefix?: T;
        quoteThemePrefix?: T;
        backToIntensiveLabel?: T;
        waitlistCtaLabel?: T;
        waitlistCtaHref?: T;
        quotes?:
          | T
          | {
              themeSlugs?: T;
              quote?: T;
              practitioner?: T;
              sourceTitle?: T;
              sourceUrl?: T;
              id?: T;
            };
        entries?:
          | T
          | {
              slug?: T;
              navLabel?: T;
              title?: T;
              subtitle?: T;
              intro?: T;
              fitTitle?: T;
              fitBullets?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              outcomesTitle?: T;
              outcomesBullets?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              faq?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}