import type { Resource } from "./types";

export const RESOURCES: Resource[] = [
  {
    slug: "attachment-theory",
    title: "Attachment Theory",
    category: "Theory",
    tags: ["attachment", "relationships", "development", "secure-base", "emotion-regulation"],
    summary:
      "Attachment theory describes how early caregiver relationships shape expectations about safety, closeness, and support. In adult relationships, attachment orientations are commonly studied in relation to stress, conflict, and patterns of connection and repair.",
    keyConcepts: [
      "Secure base and safe haven functions",
      "Attachment security, anxiety, and avoidance",
      "Internal working models and relational expectations",
      "Attachment and emotion regulation under stress",
      "Continuity and change across the lifespan",
      "Attachment in adult romantic relationships",
      "Clinical applications and limits of inference",
    ],
    citations: [
      {
        id: "cassidy-2013",
        title: "Contributions of Attachment Theory and Research",
        url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC4085672/",
        publisher: "PMC",
        year: 2013,
        kind: "reference",
      },
      {
        id: "zeanah-2011",
        title: "Practitioner Review: Clinical applications of attachment theory and research",
        url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC3670111/",
        publisher: "PMC",
        year: 2011,
        kind: "overview",
      },
      {
        id: "simpson-2017",
        title: "Adult Attachment, Stress, and Romantic Relationships",
        url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC4845754/",
        publisher: "PMC",
        year: 2017,
        kind: "reference",
      },
    ],
    worksheets: {
      previewImage: "/resources/attachment-theory/preview.webp",
      notes: "Worksheets are optional learning aids designed for reflection and discussion.",
      assets: [
        {
          id: "secure-base-map",
          label: "Secure Base Map (worksheet)",
          url: "/downloads/resources/attachment-theory/secure-base-map.pdf",
          type: "pdf",
        },
        {
          id: "attachment-reflection",
          label: "Attachment Reflection Prompts (worksheet)",
          url: "/downloads/resources/attachment-theory/attachment-reflection-prompts.pdf",
          type: "pdf",
        },
      ],
    },
  },
  {
    slug: "emotionally-focused-therapy-eft",
    title: "Emotionally Focused Therapy (EFT)",
    category: "Therapy model",
    tags: ["couples", "attachment", "emotion", "bond", "repair"],
    summary:
      "Emotionally Focused Therapy (EFT) is a structured couples therapy model that emphasizes attachment needs, emotional responsiveness, and interactional cycles. Research literature often evaluates EFT in relation to relationship satisfaction and distress outcomes.",
    keyConcepts: [
      "Attachment-based framing of couple distress",
      "Interactional cycles and negative pattern recognition",
      "Emotion as data, signal, and organizer of behavior",
      "Responsiveness, accessibility, and engagement",
      "De-escalation and new bonding events",
      "Therapist stance and process direction",
      "Evidence base and study design considerations",
    ],
    citations: [
      {
        id: "beasley-2019",
        title: "Emotionally Focused Couples Therapy: A Systematic Review and Meta-Analysis",
        url: "https://pubmed.ncbi.nlm.nih.gov/30605013/",
        publisher: "PubMed",
        year: 2019,
        kind: "meta_analysis",
      },
      {
        id: "rathgeber-2019",
        title: "The Efficacy of Emotionally Focused Couples Therapy and Behavioral Couple Therapy",
        url: "https://pubmed.ncbi.nlm.nih.gov/29781200/",
        publisher: "PubMed",
        year: 2019,
        kind: "meta_analysis",
      },
      {
        id: "bodenmann-2020",
        title: "Cognitive-Behavioral and Emotion-Focused Couple Therapy",
        url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC9645475/",
        publisher: "PMC",
        year: 2020,
        kind: "overview",
      },
    ],
    worksheets: {
      previewImage: "/resources/emotionally-focused-therapy-eft/preview.webp",
      assets: [
        {
          id: "cycle-map",
          label: "Cycle Mapping Worksheet",
          url: "/downloads/resources/emotionally-focused-therapy-eft/cycle-mapping.pdf",
          type: "pdf",
        },
      ],
    },
  },
  {
    slug: "narrative-therapy",
    title: "Narrative Therapy",
    category: "Therapy model",
    tags: ["meaning-making", "identity", "stories", "values", "re-authoring"],
    summary:
      "Narrative therapy emphasizes how people make meaning through stories about self, relationships, and context. It often focuses on externalizing problems, identifying preferred values, and building alternative stories that support agency and connection.",
    keyConcepts: [
      "Stories as frameworks for meaning and identity",
      "Externalizing problems from the person",
      "Preferred values and unique outcomes",
      "Re-authoring conversations and thickening alternatives",
      "Context, power, and social narratives",
      "Documentation practices and audience",
      "Evidence base and scope of research",
    ],
    citations: [
      {
        id: "hu-2024",
        title: "Effectiveness of narrative therapy for depressive symptoms: systematic review and meta-analysis",
        url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC11609228/",
        publisher: "PMC",
        year: 2024,
        kind: "meta_analysis",
      },
      {
        id: "conti-2022",
        title: "Systematic review of narrative therapy treatment outcomes",
        url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC9469550/",
        publisher: "PMC",
        year: 2022,
        kind: "systematic_review",
      },
      {
        id: "dane-2024",
        title: "Narrative therapy and family therapy in genetic counseling",
        url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC11907181/",
        publisher: "PMC",
        year: 2024,
        kind: "overview",
      },
    ],
    worksheets: {
      previewImage: "/resources/narrative-therapy/preview.webp",
      assets: [
        {
          id: "values-story",
          label: "Values and Preferred Story Worksheet",
          url: "/downloads/resources/narrative-therapy/values-preferred-story.pdf",
          type: "pdf",
        },
        {
          id: "externalizing-questions",
          label: "Externalizing Questions (worksheet)",
          url: "/downloads/resources/narrative-therapy/externalizing-questions.pdf",
          type: "pdf",
        },
      ],
    },
  },
  {
    slug: "gottman-method-couples-therapy",
    title: "Gottman Method Couples Therapy",
    category: "Therapy model",
    tags: ["couples", "conflict", "friendship", "repair", "communication"],
    summary:
      "Gottman Method Couples Therapy is a couples-focused approach that includes assessment, psychoeducation, and structured interventions. Research literature includes studies on relationship education and couple outcomes, with varying methods and contexts.",
    keyConcepts: [
      "Friendship and fondness as protective factors",
      "Conflict management and repair attempts",
      "Patterns associated with relationship distress",
      "Emotion regulation during conflict",
      "Skills practice and relationship rituals",
      "Workshop and therapy formats",
      "Study design variability across the literature",
    ],
    citations: [
      {
        id: "davoodvandi-2018",
        title: "Examining the Effectiveness of Gottman Couple Therapy",
        url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC6037577/",
        publisher: "PMC",
        year: 2018,
        kind: "study",
      },
      {
        id: "zahl-olsen-2024",
        title: "Effectiveness of the in-person and online Gottman Seven Principles program",
        url: "https://onlinelibrary.wiley.com/doi/10.1111/jmft.12726",
        publisher: "Wiley",
        year: 2024,
        kind: "study",
      },
      {
        id: "gottman-empirical-pdf",
        title: "The Empirical Basis for Gottman Method Therapy (PDF)",
        url: "https://www.johngottman.net/wp-content/uploads/2011/05/Empirical-Basis-for-Gottman-Method-Therapy-May2013.pdf",
        publisher: "John Gottman",
        year: 2013,
        kind: "overview",
      },
    ],
    worksheets: {
      previewImage: "/resources/gottman-method-couples-therapy/preview.webp",
      assets: [
        {
          id: "repair-checklist",
          label: "Repair Attempts Checklist (worksheet)",
          url: "/downloads/resources/gottman-method-couples-therapy/repair-checklist.pdf",
          type: "pdf",
        },
      ],
    },
  },
  {
    slug: "plissit-model",
    title: "PLISSIT Model",
    category: "Therapy model",
    tags: ["sexual-health", "psychoeducation", "permission", "counseling"],
    summary:
      "The PLISSIT model is a stepped framework often used in sexual counseling and health contexts. It organizes support into levels such as permission giving, providing limited information, offering specific suggestions, and referring for intensive therapy when needed.",
    keyConcepts: [
      "Permission giving as a foundational step",
      "Limited information and normalizing education",
      "Specific suggestions and skills practice",
      "When to refer for intensive therapy",
      "Boundaries, scope, and clinician competence",
      "Adapting the model to context",
      "Evidence base in applied settings",
    ],
    citations: [
      {
        id: "ozdemir-2024",
        title: "The Effect of Sexual Counseling Based on PLISSIT and EX-PLISSIT Models",
        url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC11390780/",
        publisher: "PMC",
        year: 2024,
        kind: "meta_analysis",
      },
      {
        id: "amini-2025",
        title: "Effect of PLISSIT model counseling on sexual quality of life (Scientific Reports)",
        url: "https://www.nature.com/articles/s41598-025-03529-z",
        publisher: "Nature",
        year: 2025,
        kind: "study",
      },
      {
        id: "banaei-pdf",
        title: "Counseling based on PLISSIT model (PDF)",
        url: "https://ijpras.com/storage/models/article/8vgZEbDKSWLXnH4h3dbXCF2aEc6XEe2lpZms9sBDTAegnUYfGulAzGLHx7ar/investigating-the-impact-of-counseling-based-on-plissit-model-on-sexual-intimacy-and-satisfaction-.pdf",
        publisher: "IJPRAS",
        kind: "study",
      },
    ],
    worksheets: {
      previewImage: "/resources/plissit-model/preview.webp",
      assets: [
        {
          id: "permission-language",
          label: "Permission Language Examples (worksheet)",
          url: "/downloads/resources/plissit-model/permission-language.pdf",
          type: "pdf",
        },
      ],
    },
  },
  {
    slug: "solution-focused-therapy",
    title: "Solution-Focused Brief Therapy (SFBT)",
    category: "Therapy model",
    tags: ["goals", "exceptions", "brief-therapy", "strengths"],
    summary:
      "Solution-Focused Brief Therapy emphasizes goal clarity, exceptions, and small steps that support progress. Research often evaluates SFBT across settings and populations, including outcomes related to distress, functioning, and goal attainment.",
    keyConcepts: [
      "Preferred future and concrete goal statements",
      "Exception finding and amplification",
      "Scaling questions for tracking change",
      "Strengths and resources orientation",
      "Brief structure and session focus",
      "Collaborative stance and language",
      "Evidence base across contexts",
    ],
    citations: [
      {
        id: "froerer-2024",
        title: "Meta-Analysis of Solution-Focused Brief Therapy",
        url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC11683447/",
        publisher: "PMC",
        year: 2024,
        kind: "meta_analysis",
      },
      {
        id: "pekala-2025",
        title: "Solution-focused brief therapy for common mental disorders (umbrella review)",
        url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC12645795/",
        publisher: "PMC",
        year: 2025,
        kind: "systematic_review",
      },
      {
        id: "zak-2024",
        title: "Effectiveness of Solution-Focused Brief Therapy: umbrella review",
        url: "https://pubmed.ncbi.nlm.nih.gov/39324877/",
        publisher: "PubMed",
        year: 2024,
        kind: "systematic_review",
      },
    ],
    worksheets: {
      previewImage: "/resources/solution-focused-therapy/preview.webp",
      assets: [
        {
          id: "preferred-future",
          label: "Preferred Future Worksheet",
          url: "/downloads/resources/solution-focused-therapy/preferred-future.pdf",
          type: "pdf",
        },
        {
          id: "scaling-tracker",
          label: "Scaling Tracker (worksheet)",
          url: "/downloads/resources/solution-focused-therapy/scaling-tracker.pdf",
          type: "pdf",
        },
      ],
    },
  },
  {
    slug: "polyvagal-theory",
    title: "Polyvagal Theory",
    category: "Theory",
    tags: ["nervous-system", "safety", "co-regulation", "stress-response"],
    summary:
      "Polyvagal theory is a framework that relates autonomic nervous system states to safety cues, social engagement, and defensive responses. It is frequently referenced in discussions of stress, trauma, and co-regulation.",
    keyConcepts: [
      "Autonomic state shifts and adaptive responding",
      "Social engagement and cues of safety",
      "Co-regulation and relational nervous system dynamics",
      "Threat detection and defensive mobilization",
      "Language precision: what is supported vs hypothesized",
      "Application in trauma-informed contexts",
      "Ongoing debate and interpretation in the literature",
    ],
    citations: [
      {
        id: "porges-frontiers-2022",
        title: "Polyvagal Theory: A Science of Safety",
        url: "https://www.frontiersin.org/journals/integrative-neuroscience/articles/10.3389/fnint.2022.871227/full",
        publisher: "Frontiers",
        year: 2022,
        kind: "overview",
      },
      {
        id: "porges-pmc-2022",
        title: "Polyvagal Theory: A Science of Safety (PMC version)",
        url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC9131189/",
        publisher: "PMC",
        year: 2022,
        kind: "overview",
      },
      {
        id: "unc-repository-2022",
        title: "Polyvagal Theory: A Science of Safety (repository record)",
        url: "https://cdr.lib.unc.edu/concern/articles/8k71ns75d",
        publisher: "UNC Repository",
        year: 2022,
        kind: "reference",
      },
    ],
    worksheets: {
      assets: [
        {
          id: "polyvagal-theory-worksheet",
          label: "Polyvagal Theory Worksheet",
          url: "/downloads/resources/polyvagal-theory/polyvagal-theory-worksheet.pdf",
          type: "pdf",
        },
      ],
    },
  },
  {
    slug: "developmental-model",
    title: "Developmental Model",
    category: "Theory",
    tags: ["differentiation", "maturity", "boundaries", "couples"],
    summary:
      "The Developmental Model frames relationship growth as a progression of maturational tasks. It emphasizes balancing connection with individuality, strengthening self-definition, and working with tension as part of long-term development.",
    keyConcepts: [
      "Differentiation and self-definition in partnership",
      "Growth through relational tension rather than avoidance",
      "Maturational tasks across stages of commitment",
      "Balancing individuality with mutual connection",
      "Clear boundaries and accountability in conflict",
      "From fusion pressure to grounded position-taking",
      "Practical development through repeated experiments",
    ],
    citations: [
      {
        id: "schnarch-crucible",
        title: "A Crucible for Love: Constructive Conflict in Marriage",
        url: "https://www.hup.harvard.edu/books/9780674173414",
        publisher: "Harvard University Press",
        year: 1998,
        kind: "reference",
      },
      {
        id: "schnarch-passionate-marriage",
        title: "The Passionate Marriage",
        url: "https://wwnorton.com/books/9780393334272",
        publisher: "W. W. Norton",
        year: 2009,
        kind: "reference",
      },
      {
        id: "couples-institute-developmental-model",
        title: "The Developmental Model",
        url: "https://www.couplesinstitute.com/the-developmental-model/",
        publisher: "The Couples Institute",
        year: 2024,
        kind: "overview",
      },
    ],
    worksheets: {
      assets: [
        {
          id: "developmental-model-worksheet",
          label: "Developmental Model Worksheet",
          url: "/downloads/resources/developmental-model/developmental-model-worksheet.pdf",
          type: "pdf",
        },
      ],
    },
  },
  {
    slug: "strengths-based-approach",
    title: "Strengths-Based Approach",
    category: "Therapy model",
    tags: ["strengths", "resources", "resilience", "agency"],
    summary:
      "Strengths-based approaches emphasize identifying and using existing capacities, resources, and protective factors. In psychotherapy and social care, strengths-based methods are discussed as complements to problem-focused assessment and intervention.",
    keyConcepts: [
      "Strengths and resources as targets for intervention",
      "Agency, competence, and resilience factors",
      "Collaborative goal setting and language",
      "Integrating strengths with risk and needs assessment",
      "Evidence base and methodological limits",
      "Contextual and cultural considerations",
      "Avoiding forced positivity or minimization",
    ],
    citations: [
      {
        id: "fluckiger-2023",
        title: "Strength-based methods: A narrative review and meta-analytic perspective",
        url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC10440292/",
        publisher: "PMC",
        year: 2023,
        kind: "systematic_review",
      },
      {
        id: "caiels-2021",
        title: "Strengths-Based Approaches in Social Work and Social Care",
        url: "https://journal.ilpnetwork.org/articles/10.31389/jltc.102",
        publisher: "Journal of Long-Term Care",
        year: 2021,
        kind: "overview",
      },
      {
        id: "caiels-2024",
        title: "Strengths-based Approaches: Perspectives from Practitioners",
        url: "https://academic.oup.com/bjsw/article/54/1/168/7238457",
        publisher: "British Journal of Social Work",
        year: 2024,
        kind: "study",
      },
    ],
    worksheets: {
      previewImage: "/resources/strengths-based-approach/preview.webp",
      assets: [
        {
          id: "strengths-inventory",
          label: "Strengths Inventory (worksheet)",
          url: "/downloads/resources/strengths-based-approach/strengths-inventory.pdf",
          type: "pdf",
        },
      ],
    },
  },
  {
    slug: "structural-family-therapy",
    title: "Structural Family Therapy",
    category: "Therapy model",
    tags: ["family-systems", "boundaries", "hierarchy", "subsystems"],
    summary:
      "Structural family therapy focuses on family organization, boundaries, and interaction patterns. Interventions often aim to shift structure in ways that support healthier functioning across subsystems and relationships.",
    keyConcepts: [
      "Family subsystems and roles",
      "Boundaries: rigid, diffuse, clear",
      "Hierarchy and parental executive functioning",
      "Enactments and interaction pattern observation",
      "Reframing and restructuring strategies",
      "Cultural context and power dynamics",
      "Empirical evidence and application areas",
    ],
    citations: [
      {
        id: "vetere-2001",
        title: "Structural Family Therapy (overview record)",
        url: "https://onlinelibrary.wiley.com/doi/abs/10.1111/1475-3588.00336",
        publisher: "Wiley",
        year: 2001,
        kind: "overview",
      },
      {
        id: "delghandi-2024",
        title: "Comparing the effectiveness of structural family therapy and mindfulness-based family therapy",
        url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC10884341/",
        publisher: "PMC",
        year: 2024,
        kind: "study",
      },
      {
        id: "sft-sage-2022",
        title: "Using Structural Family Theory in Treating Family Conflict",
        url: "https://journals.sagepub.com/doi/10.1177/10664807221123561",
        publisher: "SAGE",
        year: 2022,
        kind: "study",
      },
    ],
    worksheets: {
      previewImage: "/resources/structural-family-therapy/preview.webp",
      assets: [
        {
          id: "family-structure-map",
          label: "Family Structure Map (worksheet)",
          url: "/downloads/resources/structural-family-therapy/family-structure-map.pdf",
          type: "pdf",
        },
      ],
    },
  },
  {
    slug: "cognitive-behavioral-therapy-cbt",
    title: "Cognitive Behavioral Therapy (CBT)",
    category: "Therapy model",
    tags: ["cognition", "behavior", "skills", "thoughts", "exposure"],
    summary:
      "Cognitive Behavioral Therapy (CBT) is a skills-based approach that focuses on relationships between thoughts, feelings, and behaviors. Research on CBT is broad and includes many adaptations across conditions and settings.",
    keyConcepts: [
      "Thoughts, emotions, behaviors, and feedback loops",
      "Cognitive restructuring and perspective testing",
      "Behavioral activation and graded tasks",
      "Exposure-based learning for anxiety and trauma",
      "Skills practice and between-session work",
      "Measurement and tracking of change",
      "Adaptations and treatment fidelity",
    ],
    citations: [
      {
        id: "cbt-statpearls",
        title: "Cognitive Behavior Therapy (StatPearls)",
        url: "https://www.ncbi.nlm.nih.gov/books/NBK470241/",
        publisher: "NCBI Bookshelf",
        year: 2023,
        kind: "overview",
      },
      {
        id: "cbt-in-brief",
        title: "In brief: Cognitive behavioral therapy (CBT)",
        url: "https://www.ncbi.nlm.nih.gov/books/NBK279297/",
        publisher: "NCBI Bookshelf",
        year: 2025,
        kind: "overview",
      },
      {
        id: "rcbt-2021",
        title: "Religion-Adapted Cognitive Behavioral Therapy",
        url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC8837510/",
        publisher: "PMC",
        year: 2021,
        kind: "systematic_review",
      },
    ],
    worksheets: {
      previewImage: "/resources/cognitive-behavioral-therapy-cbt/preview.webp",
      assets: [
        {
          id: "thought-record",
          label: "Thought Record (worksheet)",
          url: "/downloads/resources/cognitive-behavioral-therapy-cbt/thought-record.pdf",
          type: "pdf",
        },
        {
          id: "behavioral-experiment",
          label: "Behavioral Experiment Plan (worksheet)",
          url: "/downloads/resources/cognitive-behavioral-therapy-cbt/behavioral-experiment.pdf",
          type: "pdf",
        },
      ],
    },
  },
  {
    slug: "sexuality",
    title: "Sexuality",
    category: "Area of interest",
    tags: ["sexual-health", "communication", "relationships", "consent"],
    summary:
      "Sexuality research spans sexual development, identity, relationship contexts, and sexual communication. Clinical frameworks often emphasize consent, accurate information, and communication skills that support safety and satisfaction.",
    keyConcepts: [
      "Sexuality as multi-dimensional: identity, behavior, meaning",
      "Consent and autonomy as foundational",
      "Sexual communication and relationship outcomes",
      "Context: culture, religion, health, and stress",
      "Desire variability across the lifespan",
      "Reducing stigma and misinformation",
      "When to seek specialized care",
    ],
    citations: [
      {
        id: "sexual-communication-meta",
        title: "Dimensions of Couples' Sexual Communication: meta-analysis",
        url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC9153093/",
        publisher: "PMC",
        year: 2021,
        kind: "meta_analysis",
      },
      {
        id: "plissit-meta-2024",
        title: "Sexual counseling based on PLISSIT and EX-PLISSIT models",
        url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC11390780/",
        publisher: "PMC",
        year: 2024,
        kind: "meta_analysis",
      },
      {
        id: "cdc-sexual-violence-definition",
        title: "CDC: About Sexual Violence",
        url: "https://www.cdc.gov/sexual-violence/about/index.html",
        publisher: "CDC",
        year: 2024,
        kind: "overview",
      },
    ],
    worksheets: {
      previewImage: "/resources/sexuality/preview.webp",
      assets: [
        {
          id: "sexual-communication-prompts",
          label: "Sexual Communication Prompts (worksheet)",
          url: "/downloads/resources/sexuality/sexual-communication-prompts.pdf",
          type: "pdf",
        },
      ],
    },
  },
  {
    slug: "long-term-relationships",
    title: "Long-Term Relationships",
    category: "Area of interest",
    tags: ["relationship-quality", "commitment", "maintenance", "satisfaction"],
    summary:
      "Long-term relationship research examines predictors of relationship quality over time, including commitment, appreciation, conflict processes, attachment, and contextual stress. Findings vary across samples and methods but often highlight relationship-specific factors as central.",
    keyConcepts: [
      "Relationship quality and stability as distinct outcomes",
      "Commitment and responsiveness as common predictors",
      "Conflict patterns and repair over time",
      "Attachment orientations and stress processes",
      "Appreciation and perceived partner investment",
      "Contextual factors: health, finances, parenting",
      "Limits of self-report and sampling biases",
    ],
    citations: [
      {
        id: "joel-2020-pnas",
        title: "Machine learning predictors of relationship quality across longitudinal couples studies (PNAS)",
        url: "https://pubmed.ncbi.nlm.nih.gov/32719123/",
        publisher: "PubMed",
        year: 2020,
        kind: "study",
      },
      {
        id: "joel-2020-pdf",
        title: "PNAS paper PDF (Joel et al., 2020)",
        url: "https://sites.lsa.umich.edu/whirl/wp-content/uploads/sites/792/2020/08/Joel-et-al-2020-PNAS.pdf",
        publisher: "Repository",
        year: 2020,
        kind: "reference",
      },
      {
        id: "freeman-2023",
        title: "Romantic Duration, Relationship Quality, and Attachment Insecurity",
        url: "https://europepmc.org/article/pmc/pmc9820285",
        publisher: "Europe PMC",
        year: 2023,
        kind: "study",
      },
    ],
    worksheets: {
      previewImage: "/resources/long-term-relationships/preview.webp",
      assets: [
        {
          id: "relationship-maintenance",
          label: "Relationship Maintenance Plan (worksheet)",
          url: "/downloads/resources/long-term-relationships/relationship-maintenance-plan.pdf",
          type: "pdf",
        },
      ],
    },
  },
  {
    slug: "communication-in-relationships",
    title: "Communication in Relationships",
    category: "Area of interest",
    tags: ["communication", "conflict", "repair", "interaction"],
    summary:
      "Communication research in romantic relationships often evaluates how interaction patterns relate to satisfaction and stability. Findings commonly distinguish between positive and negative interaction processes and the ways they change over time.",
    keyConcepts: [
      "Positive and negative interaction patterns",
      "Repair and re-entry after conflict",
      "Behavioral observation vs self-report measurement",
      "Accommodation and responsiveness processes",
      "Longitudinal change and directionality questions",
      "Stress spillover into communication",
      "Skill-building and practice considerations",
    ],
    citations: [
      {
        id: "lavner-2016",
        title: "Does Couples' Communication Predict Marital Satisfaction, or Does Marital Satisfaction Predict Communication?",
        url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC4852543/",
        publisher: "PMC",
        year: 2016,
        kind: "study",
      },
      {
        id: "johnson-2021",
        title: "Within-Couple Associations Between Communication and Relationship Satisfaction",
        url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC8915221/",
        publisher: "PMC",
        year: 2021,
        kind: "overview",
      },
      {
        id: "de-netto-2021",
        title: "Communication, the Heart of a Relationship",
        url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC8710473/",
        publisher: "PMC",
        year: 2021,
        kind: "study",
      },
    ],
    worksheets: {
      previewImage: "/resources/communication-in-relationships/preview.webp",
      assets: [
        {
          id: "repair-script",
          label: "Repair Script Practice (worksheet)",
          url: "/downloads/resources/communication-in-relationships/repair-script.pdf",
          type: "pdf",
        },
      ],
    },
  },
  {
    slug: "body-acceptance",
    title: "Body Acceptance",
    category: "Area of interest",
    tags: ["body-image", "weight-stigma", "health-equity", "self-compassion"],
    summary:
      "Body acceptance resources often address body image, weight stigma, and the relationship between well-being and health behaviors. A weight-neutral approach is discussed in public health literature with attention to both benefits and limitations of existing evidence.",
    keyConcepts: [
      "Body image and well-being as related but distinct constructs",
      "Weight stigma and mental health impacts",
      "Weight-neutral health promotion approaches",
      "Intuitive eating and sustainable behavior change",
      "Evidence quality and limitations in intervention research",
      "Cultural context and identity considerations",
      "Clinician responsibility to avoid harm",
    ],
    citations: [
      {
        id: "penney-2015",
        title: "The Health at Every Size Paradigm and Obesity",
        url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC4386524/",
        publisher: "PMC",
        year: 2015,
        kind: "overview",
      },
      {
        id: "suarez-2024",
        title: "Effects of Health at Every Size based interventions on health outcomes",
        url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC11493725/",
        publisher: "PMC",
        year: 2024,
        kind: "systematic_review",
      },
      {
        id: "bombak-2014",
        title: "Obesity, Health at Every Size, and Public Health Policy",
        url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC3935663/",
        publisher: "PMC",
        year: 2014,
        kind: "overview",
      },
    ],
    worksheets: {
      previewImage: "/resources/body-acceptance/preview.webp",
      assets: [
        {
          id: "body-respect",
          label: "Body Respect Reflection (worksheet)",
          url: "/downloads/resources/body-acceptance/body-respect-reflection.pdf",
          type: "pdf",
        },
      ],
    },
  },
  {
    slug: "post-partum",
    title: "Postpartum",
    category: "Area of interest",
    tags: ["perinatal", "mental-health", "support", "adjustment"],
    summary:
      "Postpartum adjustment can include changes in mood, anxiety, identity, sleep, and relationship dynamics. Clinical guidance emphasizes screening, support, and appropriate referral when symptoms are intense, persistent, or impair functioning.",
    keyConcepts: [
      "Postpartum depression and anxiety basics",
      "Screening and early identification",
      "Sleep disruption and stress physiology",
      "Support systems and practical care planning",
      "Relationship strain and role shifts",
      "When to seek professional help",
      "Protective factors and recovery pathways",
    ],
    citations: [
      {
        id: "acog-ppd-faq",
        title: "ACOG FAQ: Postpartum Depression",
        url: "https://www.acog.org/womens-health/faqs/postpartum-depression",
        publisher: "ACOG",
        kind: "guideline",
      },
      {
        id: "acog-resources",
        title: "ACOG: Educational Resources for Providers, Patients, and Families",
        url: "https://www.acog.org/programs/perinatal-mental-health/educational-resources-for-providers-patients-and-families",
        publisher: "ACOG",
        kind: "reference",
      },
      {
        id: "acog-mental-health-video",
        title: "ACOG Explains: Mental Health and Pregnancy",
        url: "https://www.acog.org/womens-health/videos/mental-health-and-pregnancy",
        publisher: "ACOG",
        kind: "overview",
      },
    ],
    worksheets: {
      previewImage: "/resources/post-partum/preview.webp",
      assets: [
        {
          id: "support-plan",
          label: "Postpartum Support Plan (worksheet)",
          url: "/downloads/resources/post-partum/postpartum-support-plan.pdf",
          type: "pdf",
        },
      ],
    },
  },
  {
    slug: "faith-transitions",
    title: "Faith Transitions",
    category: "Area of interest",
    tags: ["religion", "identity", "meaning", "community", "change"],
    summary:
      "Faith transitions can involve shifts in beliefs, community belonging, identity, and meaning-making. Research on religiosity and mental health includes both protective and harmful associations depending on context, support, and stressors.",
    keyConcepts: [
      "Identity shifts and meaning reconstruction",
      "Community belonging and relational impact",
      "Grief, relief, and mixed emotional responses",
      "Moral injury and spiritual struggle concepts",
      "Protective factors: support and coherence",
      "Risks: isolation, shame, and conflict",
      "When to seek additional support",
    ],
    citations: [
      {
        id: "lucchetti-2021",
        title: "Spirituality, religiousness, and mental health: A review",
        url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC8462234/",
        publisher: "PMC",
        year: 2021,
        kind: "systematic_review",
      },
      {
        id: "aggarwal-2023",
        title: "Religiosity and spirituality in prevention and management of depression: review",
        url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC10563335/",
        publisher: "PMC",
        year: 2023,
        kind: "overview",
      },
      {
        id: "vanderweele-2025",
        title: "Religion and Mental Health: Is the Relationship Causal?",
        url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC12133908/",
        publisher: "PMC",
        year: 2025,
        kind: "overview",
      },
    ],
    worksheets: {
      previewImage: "/resources/faith-transitions/preview.webp",
      assets: [
        {
          id: "values-bridge",
          label: "Values Bridge (worksheet)",
          url: "/downloads/resources/faith-transitions/values-bridge.pdf",
          type: "pdf",
        },
      ],
    },
  },
  {
    slug: "mixed-faith-relationships",
    title: "Mixed-Faith Relationships",
    category: "Area of interest",
    tags: ["interfaith", "marriage", "values", "conflict", "support"],
    summary:
      "Mixed-faith and interfaith relationships may involve differences in values, practice, family expectations, and community belonging. Research includes both qualitative and quantitative work on how couples navigate religious differences and build shared agreements.",
    keyConcepts: [
      "Clarifying shared values vs doctrinal differences",
      "Family systems and community pressures",
      "Creating agreements on holidays, rituals, and children",
      "Communication strategies for recurring differences",
      "Emotional regulation under identity threat",
      "Support systems and boundary setting",
      "Respectful curiosity and conflict de-escalation",
    ],
    citations: [
      {
        id: "interfaith-strengths-2022",
        title: "Strengths and Strategies in Interfaith Marriages",
        url: "https://www.tandfonline.com/doi/abs/10.1080/01494929.2022.2093311?journalCode=wmfr20&src=",
        publisher: "Taylor & Francis",
        year: 2022,
        kind: "study",
      },
      {
        id: "navigate-interfaith-2025-pdf",
        title: "Navigating Religious Differences in Interfaith Relationships (PDF)",
        url: "https://ijbmc.org/index.php/ijbmc/article/download/913/606/8737",
        publisher: "IJBMC",
        year: 2025,
        kind: "study",
      },
      {
        id: "religion-marital-satisfaction-2019",
        title: "Religious Affiliation and Marital Satisfaction",
        url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC6923244/",
        publisher: "PMC",
        year: 2019,
        kind: "study",
      },
    ],
    worksheets: {
      previewImage: "/resources/mixed-faith-relationships/preview.webp",
      assets: [
        {
          id: "shared-agreements",
          label: "Shared Agreements Worksheet",
          url: "/downloads/resources/mixed-faith-relationships/shared-agreements.pdf",
          type: "pdf",
        },
      ],
    },
  },
  {
    slug: "political-ideology-divides",
    title: "Political Ideology Divides",
    category: "Area of interest",
    tags: ["politics", "values", "conflict", "polarization", "communication"],
    summary:
      "Political differences can activate concerns about values, identity, and belonging. Research on political dissimilarity in romantic relationships examines when differences predict distress and when other shared domains and skills buffer impact.",
    keyConcepts: [
      "Political dissimilarity vs perceived value differences",
      "Identity threat and escalation dynamics",
      "News consumption and conflict triggers",
      "Boundary setting around media and discussion timing",
      "Repair and de-escalation strategies",
      "Respectful curiosity and perspective-taking limits",
      "Co-existing values and shared life domains",
    ],
    citations: [
      {
        id: "gordon-jpsp-pdf",
        title: "Political Dissimilarity in Romantic Relationships (JPSP PDF)",
        url: "https://sites.lsa.umich.edu/whirl/wp-content/uploads/sites/792/2024/05/Gordon-et-al-in-press-JPSP.pdf",
        publisher: "Repository",
        year: 2024,
        kind: "study",
      },
      {
        id: "uiuc-news-study-2024",
        title: "Study: News media trigger conflict for romantic couples with differing political views",
        url: "https://las.illinois.edu/news/2024-01-19/study-news-media-trigger-conflict-romantic-couples-differing-political-views",
        publisher: "University of Illinois",
        year: 2024,
        kind: "overview",
      },
      {
        id: "apa-jpsp-journal",
        title: "Journal of Personality and Social Psychology (journal info)",
        url: "https://www.apa.org/pubs/journals/psp",
        publisher: "APA",
        kind: "reference",
      },
    ],
    worksheets: {
      previewImage: "/resources/political-ideology-divides/preview.webp",
      assets: [
        {
          id: "conversation-boundaries",
          label: "Conversation Boundaries (worksheet)",
          url: "/downloads/resources/political-ideology-divides/conversation-boundaries.pdf",
          type: "pdf",
        },
      ],
    },
  },
  {
    slug: "lgbtqia-support",
    title: "LGBTQIA+ Support",
    category: "Area of interest",
    tags: ["lgbtqia", "affirming-care", "minority-stress", "relationships"],
    summary:
      "LGBTQIA+ support resources often emphasize affirming care, minority stress awareness, and culturally responsive practice. Professional guidelines highlight the importance of understanding diversity within sexual minority communities and reducing stigma-related harm.",
    keyConcepts: [
      "Affirming language and respect for identity",
      "Minority stress and its mental health impacts",
      "Family and community context",
      "Relationship stressors and resilience factors",
      "Intersectionality and cultural humility",
      "Safety and confidentiality considerations",
      "Evidence-informed practice guidelines",
    ],
    citations: [
      {
        id: "apa-guidelines-pdf-2021",
        title: "APA: Guidelines for Psychological Practice with Sexual Minority Persons (PDF)",
        url: "https://www.apa.org/about/policy/psychological-sexual-minority-persons.pdf",
        publisher: "APA",
        year: 2021,
        kind: "guideline",
      },
      {
        id: "nakamura-2022",
        title: "Executive summary of APA Guidelines for Sexual Minority Persons",
        url: "https://pubmed.ncbi.nlm.nih.gov/35143229/",
        publisher: "PubMed",
        year: 2022,
        kind: "overview",
      },
      {
        id: "apa-monitor-2022",
        title: "APA Monitor: Updated guidelines for sexual minority people",
        url: "https://www.apa.org/monitor/2022/11/guidelines-sexual-minority-resilience",
        publisher: "APA",
        year: 2022,
        kind: "overview",
      },
    ],
    worksheets: {
      previewImage: "/resources/lgbtqia-support/preview.webp",
      assets: [
        {
          id: "support-map",
          label: "Support Map (worksheet)",
          url: "/downloads/resources/lgbtqia-support/support-map.pdf",
          type: "pdf",
        },
      ],
    },
  },
  {
    slug: "dating-after-divorce",
    title: "Dating After Divorce",
    category: "Area of interest",
    tags: ["divorce", "dating", "repartnering", "family-systems"],
    summary:
      "Dating after divorce can involve changes in identity, parenting dynamics, and emotional recovery. Research includes studies on post-divorce dating transitions and associations with well-being and family adjustment.",
    keyConcepts: [
      "Divorce-stress-adaptation and recovery pathways",
      "Timing and readiness for dating",
      "Co-parenting context and boundary setting",
      "Children’s adjustment considerations",
      "Attachment, trust, and vulnerability",
      "Communication and pacing in new relationships",
      "Safety and support systems",
    ],
    citations: [
      {
        id: "langlais-2016",
        title: "Consequences of Dating for Post-Divorce Maternal Well-Being",
        url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC5061053/",
        publisher: "PMC",
        year: 2016,
        kind: "study",
      },
      {
        id: "deanda-2021",
        title: "Examining Children's Problem Behaviors and Mothers' Dating",
        url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC8525835/",
        publisher: "PMC",
        year: 2021,
        kind: "study",
      },
      {
        id: "xiao-2021",
        title: "Is It OK If Mommy Dates? Post-divorce dating transitions and child adjustment",
        url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC11620120/",
        publisher: "PMC",
        year: 2021,
        kind: "study",
      },
    ],
    worksheets: {
      previewImage: "/resources/dating-after-divorce/preview.webp",
      assets: [
        {
          id: "dating-readiness",
          label: "Dating Readiness Checklist (worksheet)",
          url: "/downloads/resources/dating-after-divorce/dating-readiness.pdf",
          type: "pdf",
        },
      ],
    },
  },
  {
    slug: "infidelity",
    title: "Infidelity",
    category: "Area of interest",
    tags: ["betrayal", "trust", "repair", "trauma", "couples"],
    summary:
      "Infidelity is commonly defined as a violation of a couple’s assumed or stated agreement about exclusivity. Research examines prevalence, causes, consequences, and repair processes, including impacts on relationship quality and psychological distress.",
    keyConcepts: [
      "Definitions: sexual, emotional, combined, online",
      "Disclosure, discovery, and acute stress responses",
      "Attachment, vulnerability, and relationship context",
      "Repair tasks: accountability, transparency, boundaries",
      "Forgiveness as a process, not a requirement",
      "Risk assessment for coercion or violence",
      "Role of couples therapy and stabilization",
    ],
    citations: [
      {
        id: "rokach-2023",
        title: "Love and Infidelity: Causes and Consequences",
        url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC10002055/",
        publisher: "PMC",
        year: 2023,
        kind: "overview",
      },
      {
        id: "mitchell-2025",
        title: "Staying Together After Infidelity: Exploration of literature",
        url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC12745057/",
        publisher: "PMC",
        year: 2025,
        kind: "study",
      },
      {
        id: "ghiasi-2023",
        title: "Interplay of attachment styles and marital infidelity",
        url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC10754894/",
        publisher: "PMC",
        year: 2023,
        kind: "systematic_review",
      },
    ],
    worksheets: {
      previewImage: "/resources/infidelity/preview.webp",
      assets: [
        {
          id: "repair-plan",
          label: "Repair Plan Outline (worksheet)",
          url: "/downloads/resources/infidelity/repair-plan-outline.pdf",
          type: "pdf",
        },
      ],
    },
  },
  {
    slug: "healing-from-sexual-trauma",
    title: "Healing From Sexual Trauma",
    category: "Area of interest",
    tags: ["trauma", "ptsd", "sexual-violence", "recovery", "safety"],
    summary:
      "Healing from sexual trauma may involve addressing acute stress responses, PTSD symptoms, shame, and changes in relationships and sexuality. Evidence-based guidelines emphasize assessment, safety planning, and trauma-focused interventions when appropriate.",
    keyConcepts: [
      "Consent violations and trauma responses",
      "PTSD symptoms and functional impact",
      "Shame and self-blame dynamics",
      "Stabilization: sleep, support, and safety planning",
      "Trauma-focused therapies and pacing",
      "Medical and legal resources as needed",
      "Crisis and support hotlines",
    ],
    citations: [
      {
        id: "va-dod-ptsd-full",
        title: "VA/DoD Clinical Practice Guideline: Management of PTSD and Acute Stress Disorder (PDF)",
        url: "https://www.healthquality.va.gov/HEALTHQUALITY/guidelines/MH/ptsd/VA-DoD-CPG-PTSD-Full-CPG-Edited-111624-V5-81825.pdf",
        publisher: "VA/DoD",
        year: 2023,
        kind: "guideline",
      },
      {
        id: "istss-guidelines-pdf",
        title: "ISTSS PTSD Prevention and Treatment Guidelines (PDF)",
        url: "https://istss.org/wp-content/uploads/2024/08/ISTSS_PreventionTreatmentGuidelines_FNL-March-19-2019.pdf",
        publisher: "ISTSS",
        year: 2019,
        kind: "guideline",
      },
      {
        id: "cdc-sexual-violence",
        title: "CDC: About Sexual Violence",
        url: "https://www.cdc.gov/sexual-violence/about/index.html",
        publisher: "CDC",
        year: 2024,
        kind: "overview",
      },
      {
        id: "rainn-hotline",
        title: "RAINN: National Sexual Assault Hotline",
        url: "https://rainn.org/help-and-healing/hotline/",
        publisher: "RAINN",
        kind: "reference",
      },
    ],
    worksheets: {
      previewImage: "/resources/healing-from-sexual-trauma/preview.webp",
      assets: [
        {
          id: "grounding-tools",
          label: "Grounding Tools List (worksheet)",
          url: "/downloads/resources/healing-from-sexual-trauma/grounding-tools.pdf",
          type: "pdf",
        },
      ],
    },
  },
  {
    slug: "pre-commitment-counseling",
    title: "Pre-Commitment Counseling",
    category: "Area of interest",
    tags: ["premarital", "decision-making", "values", "commitment", "skills"],
    summary:
      "Pre-commitment counseling and relationship education research examines how structured programs and counseling approaches relate to relationship skills and outcomes. Evidence varies across program types, populations, and study designs.",
    keyConcepts: [
      "Clarifying shared values and expectations",
      "Communication and conflict skill-building",
      "Agreements about money, family, and roles",
      "Attachment and emotional responsiveness topics",
      "Prevention vs intervention framing",
      "Evidence strength and heterogeneity across studies",
      "Cultural fit and accessibility considerations",
    ],
    citations: [
      {
        id: "acf-systematic-review",
        title: "Systematic Review of Impact of Marriage and Relationship Education (PDF)",
        url: "https://acf.gov/sites/default/files/documents/opre/systematic_rev.pdf",
        publisher: "ACF",
        kind: "systematic_review",
      },
      {
        id: "carroll-doherty-2003",
        title: "Evaluating the Effectiveness of Premarital Prevention Programs (journal record)",
        url: "https://onlinelibrary.wiley.com/doi/abs/10.1111/j.1741-3729.2003.00105.x",
        publisher: "Wiley",
        year: 2003,
        kind: "meta_analysis",
      },
      {
        id: "acog-relationship-education-mention",
        title: "ACF systematic review document landing page",
        url: "https://acf.gov/sites/default/files/documents/opre/systematic_rev.pdf",
        publisher: "ACF",
        kind: "reference",
      },
    ],
    worksheets: {
      previewImage: "/resources/pre-commitment-counseling/preview.webp",
      assets: [
        {
          id: "topic-agreements",
          label: "Topic Agreements Worksheet",
          url: "/downloads/resources/pre-commitment-counseling/topic-agreements.pdf",
          type: "pdf",
        },
      ],
    },
  },
  {
    slug: "parent-child-relationships",
    title: "Parent and Child Relationships",
    category: "Area of interest",
    tags: ["parenting", "attachment", "development", "secure-base"],
    summary:
      "Parent and child relationships are studied in relation to attachment, emotion regulation, development, and stress responses. Research spans infancy through adolescence and includes both observational and intervention-focused work.",
    keyConcepts: [
      "Sensitive responsiveness and attachment security",
      "Secure base support for exploration",
      "Emotion coaching and co-regulation",
      "Impact of stress and adversity on caregiving",
      "Repair after rupture in parent-child relationships",
      "Developmental stages and changing needs",
      "Interventions that support caregiving capacity",
    ],
    citations: [
      {
        id: "cassidy-2013-repeat",
        title: "Contributions of Attachment Theory and Research",
        url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC4085672/",
        publisher: "PMC",
        year: 2013,
        kind: "reference",
      },
      {
        id: "zeanah-2011-repeat",
        title: "Practitioner Review: Clinical applications of attachment theory and research",
        url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC3670111/",
        publisher: "PMC",
        year: 2011,
        kind: "overview",
      },
      {
        id: "bosmans-2022",
        title: "A Learning Theory Approach to Attachment Theory",
        url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC8801239/",
        publisher: "PMC",
        year: 2022,
        kind: "overview",
      },
    ],
    worksheets: {
      previewImage: "/resources/parent-child-relationships/preview.webp",
      assets: [
        {
          id: "repair-and-reconnect",
          label: "Repair and Reconnect Plan (worksheet)",
          url: "/downloads/resources/parent-child-relationships/repair-and-reconnect.pdf",
          type: "pdf",
        },
      ],
    },
  },
  {
    slug: "religious-shame-and-trauma",
    title: "Religious Shame and Trauma",
    category: "Area of interest",
    tags: ["shame", "religion", "trauma-informed", "identity", "recovery"],
    summary:
      "Religious shame and trauma discussions often address chronic shame formation, identity conflict, and experiences of coercion or harm in religious settings. Trauma-informed resources emphasize safety, choice, collaboration, trust, and empowerment.",
    keyConcepts: [
      "Shame as a social and internal experience",
      "Chronic shame formation and identity conflict",
      "Coercion, control, and boundary violations",
      "Trauma-informed principles and harm reduction",
      "Support systems and safe community building",
      "Clinician cultural humility and context",
      "Referral pathways when symptoms are severe",
    ],
    citations: [
      {
        id: "downie-2022",
        title: "Christian Shame and Religious Trauma",
        url: "https://www.mdpi.com/2077-1444/13/10/925",
        publisher: "MDPI",
        year: 2022,
        kind: "study",
      },
      {
        id: "samhsa-tip-57-pdf",
        title: "SAMHSA TIP 57: Trauma-Informed Care in Behavioral Health Services (PDF)",
        url: "https://library.samhsa.gov/sites/default/files/sma15-4420.pdf",
        publisher: "SAMHSA",
        year: 2014,
        kind: "guideline",
      },
      {
        id: "channell-2022",
        title: "Trauma-related shame, religiosity, and hazardous substance use",
        url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC10121753/",
        publisher: "PMC",
        year: 2022,
        kind: "study",
      },
    ],
    worksheets: {
      previewImage: "/resources/religious-shame-and-trauma/preview.webp",
      assets: [
        {
          id: "shame-to-needs",
          label: "From Shame to Needs (worksheet)",
          url: "/downloads/resources/religious-shame-and-trauma/shame-to-needs.pdf",
          type: "pdf",
        },
      ],
    },
  },
  {
    slug: "desire-differences-and-intimacy",
    title: "Desire Differences and Intimacy",
    category: "Area of interest",
    tags: ["desire", "intimacy", "sexual-communication", "relationships"],
    summary:
      "Desire differences are common in long-term relationships and can be shaped by stress, health, context, and relational dynamics. Research often focuses on sexual communication, expectation management, and coordinated approaches to intimacy that fit both partners.",
    keyConcepts: [
      "Desire discrepancy as a common relational pattern",
      "Contextual factors: stress, sleep, health, and workload",
      "Sexual communication quality and relational outcomes",
      "Consent and pacing in intimacy planning",
      "Reducing pursue-withdraw interaction cycles",
      "Collaborative agreements and flexibility",
      "When to include specialized sexual counseling",
    ],
    citations: [
      {
        id: "sexual-communication-meta-repeat",
        title: "Dimensions of Couples' Sexual Communication: meta-analysis",
        url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC9153093/",
        publisher: "PMC",
        year: 2021,
        kind: "meta_analysis",
      },
      {
        id: "plissit-meta-repeat",
        title: "Sexual counseling based on PLISSIT and EX-PLISSIT models",
        url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC11390780/",
        publisher: "PMC",
        year: 2024,
        kind: "meta_analysis",
      },
      {
        id: "cbt-intimacy-overview",
        title: "In brief: Cognitive behavioral therapy (CBT)",
        url: "https://www.ncbi.nlm.nih.gov/books/NBK279297/",
        publisher: "NCBI Bookshelf",
        year: 2025,
        kind: "overview",
      },
    ],
    worksheets: {
      previewImage: "/resources/desire-differences-and-intimacy/preview.webp",
      assets: [
        {
          id: "intimacy-pacing-plan",
          label: "Intimacy Pacing Plan (worksheet)",
          url: "/downloads/resources/desire-differences-and-intimacy/intimacy-pacing-plan.pdf",
          type: "pdf",
        },
      ],
    },
  },
];
